title: "Klouds.in"
description: "Cloud, Data & AI Consulting â€” AI Lab as a Service for Campus Learning"
url: "https://klouds.in"
theme: jekyll-theme-modernist

author:
  name: "Kannan Gopalan"
  email: "kannangopalan@klouds.in"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - about.md
  - services.md
  - blog.md
